---
- name: Install Nginx
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
  - epel-release
  - nginx

#- name: ensure dir exists
#  file: path="{{item}}" state=directory
#  with_items:
#  - /etc/nginx/sites-available
#  - /etc/nginx/sites-enabled


- name: remove default site
  file: path='/etc/nginx/conf.d/default.conf' state=absent


- name: add site
  template: src=roles/nginx/templates/site.conf.j2  dest=/etc/nginx/conf.d/wordpress.conf  owner=root group=root mode=0644
#  template: src=roles/nginx/templates/site.conf.j2  dest=/etc/nginx/sites-available/wordpress  owner=root group=root mode=0644

#- name: enable site
#  file: src='/etc/nginx/sites-available/wordpress'  dest='/etc/nginx/sites-enabled/wordpress'  state=link

- name: nginx restart
  service: name=nginx  state=restarted
