--- 

- hosts: proxy
  roles:
    - nginx

- hosts: app 
  roles: 
    - common
    - { role: personnage.php }
  vars:
   php_fpm_pools:
     - name: www_8005
       listen: "127.0.0.1:8005"
       user: "nginx"
       group: "nginx"
       listen.owner: "nginx"
       listen.group: "nginx"
     - name: www_8006
       listen: "127.0.0.1:8006"
       user: "nginx"
       group: "nginx"
       listen.owner: "nginx"
       listen.group: "nginx"


- hosts: db
  roles: 
    - role: mstantoncook.mysql
  vars_files: 
    - group_vars/db

- hosts: web01
  roles: 
    - wordpress
  vars: 
    wp_db_host: localhost
    wp_db_name: wp_db
    wp_db_password: wp_pass
    wp_db_user: wp_user
    wp_install_dir: /var/sites/awesome_wordpress_site01
    wp_version: 4.0

#- hosts: web02
#  roles: 
#    - wordpress
#  vars: 
#    wp_db_host: localhost
#    wp_db_name: wp_db2
#    wp_db_password: wb_pass2
#    wp_db_user: wp_user2
#    wp_install_dir: /var/sites/awesome_wordpress_site02
#    wp_version: 4.0
#
